services:
  - type: web
    name: fittrack-ai
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install --prefix client && npm run build --prefix client && npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://yyotube1487:Yn9MIAfrxokvkaXy@clusteryedid.zfna7jv.mongodb.net/fittrack-ai?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: fittrack-ai-super-secret-key-2026
      - key: NODE_VERSION
        value: 20.11.0
