import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  he: {
    // App name
    appName: 'Areto',

    // Tabs
    tabOverview: 'סקירה כללית',
    tabWorkout: 'תוכנית אימונים',
    tabNutrition: 'תזונה',
    tabGoals: 'יעדים',
    tabProgress: 'התקדמות',
    tabSettings: 'הגדרות',

    // Auth
    loginTitle: 'התחבר לחשבון שלך',
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אימות סיסמה',
    loginBtn: 'התחברות',
    loggingIn: 'מתחבר...',
    registerBtn: 'הרשמה',
    registering: 'נרשם...',
    registerSubtitle: 'צור חשבון חדש והתחל לעקוב אחרי ההתקדמות שלך',
    noAccount: 'עדיין אין לך חשבון?',
    registerHere: 'הירשם כאן',
    hasAccount: 'יש לך כבר חשבון?',
    loginHere: 'התחבר כאן',
    fillAllFields: 'יש למלא את כל השדות',
    passwordMin: 'הסיסמה חייבת להכיל לפחות 8 תווים וספרה אחת',
    passwordMismatch: 'הסיסמאות אינן תואמות',
    passwordPlaceholder: 'לפחות 6 תווים',
    confirmPlaceholder: 'הזן את הסיסמה שוב',
    logout: 'התנתקות',
    forgotPassword: 'שכחת סיסמה?',
    resetPassword: 'איפוס סיסמה',
    sendCode: 'שלח קוד',
    sendingCode: 'שולח...',
    enterCode: 'הזן את הקוד שנשלח לאימייל',
    codePlaceholder: 'קוד בן 6 ספרות',
    newPassword: 'סיסמה חדשה',
    resetBtn: 'אפס סיסמה',
    resetting: 'מאפס...',
    codeSent: 'קוד נשלח לאימייל שלך',
    passwordResetSuccess: 'הסיסמה שונתה בהצלחה! התחבר עם הסיסמה החדשה',
    backToLogin: 'חזרה להתחברות',
    codeExpired: 'הקוד פג תוקף',
    wrongCode: 'קוד שגוי',

    // Onboarding
    nameLabel: 'שם פרטי:',
    namePlaceholder: 'שם פרטי',
    onboardingTitle: 'בוא נכיר אותך',
    onboardingSubtitle: 'ספר לנו קצת על עצמך כדי שנתאים לך תוכנית אישית',
    gender: 'מין',
    male: 'גבר',
    female: 'אישה',
    age: 'גיל',
    heightLabel: 'גובה (ס"מ)',
    weightLabel: 'משקל (ק"ג)',
    bodyFat: 'אחוז שומן (אופציונלי)',
    goalLabel: 'מטרה',
    workoutsPerWeek: 'מספר אימונים בשבוע',
    workoutsUnit: 'אימונים',
    experienceLabel: 'רמת ניסיון',
    startJourney: 'התחל את המסע שלך',
    saving: 'שומר...',
    fillRequired: 'יש למלא את כל השדות הנדרשים',

    // Goals
    goalBulk: 'עלייה במסה',
    goalCut: 'חיטוב',
    goalMaintain: 'שמירה',
    goalBulkDesc: 'בניית שריר ועלייה במשקל',
    goalCutDesc: 'ירידה באחוזי שומן עם שימור שריר',
    goalMaintainDesc: 'שמירה על המשקל הנוכחי',

    // Experience
    expBeginner: 'מתחיל',
    expIntermediate: 'בינוני',
    expAdvanced: 'מתקדם',
    expBeginnerDesc: 'פחות מ-6 חודשי אימון',
    expIntermediateDesc: '6 חודשים עד 2 שנים',
    expAdvancedDesc: 'מעל 2 שנות אימון',

    // Overview
    hello: 'שלום!',
    helloName: 'שלום',
    goal: 'מטרה',
    weight: 'משקל',
    kg: 'ק"ג',
    workoutsWeek: 'אימונים בשבוע',
    caloriesToday: 'קלוריות היום',
    proteinToday: 'חלבון היום',
    workoutStreak: 'רצף אימונים',
    dailyBurn: 'שריפה יומית (קלוריות)',
    burnedToday: 'נשרף היום מאימונים',
    tipCalories: 'סה"כ אנרגיה שהגוף צריך ביום',
    tipProtein: 'בניית שריר ותיקון רקמות - בשר, ביצים, קטניות',
    tipCarbs: 'מקור האנרגיה העיקרי - לחם, אורז, פירות',
    tipFat: 'הורמונים ובריאות - שמן זית, אבוקדו, אגוזים',
    tipFiber: 'בריאות מעיים ושובע - ירקות, פירות, דגנים מלאים',
    dailyProgress: 'התקדמות יומית',
    calories: 'קלוריות',
    protein: 'חלבון',
    carbs: 'פחמימות',
    fat: 'שומן',
    fiber: 'סיבים',
    kcal: 'קלוריות',
    grams: 'גרם',
    gramsPerKg: 'גרם/ק"ג',
    yourNutritionTargets: 'יעדי התזונה שלך',
    dailyCalorieTarget: 'יעד קלוריות יומי',
    proteinTip: 'טיפ:',
    proteinPerMealText: 'חלבון לארוחה',
    mealsPerDay: 'ארוחות ביום',
    optimalMuscle: 'לבניית שריר מיטבית',
    gainTarget: 'יעד עלייה:',
    kgPerMonth: 'ק"ג בחודש',
    kgPerWeek: 'ק"ג בשבוע',
    maintenance: 'שמירה:',
    weightStable: 'המשקל צריך להישאר יציב (תנודות של עד ±',
    normalFluctuation: 'ק"ג זה נורמלי)',
    weeklyTarget: 'יעד שבועי:',
    lossOf: 'ירידה של',
    bodyWeightLoss: '(0.5%-1.0% ממשקל הגוף לשמירה על שריר)',
    restBurn: 'שריפה במנוחה:',
    dailyBurnLabel: 'שריפה יומית:',

    // Nutrition Tracker
    nutritionTracking: 'מעקב תזונה',
    nutritionSubtitle: 'הזן את מה שאכלת והמערכת תחשב את הערכים התזונתיים',
    addMeal: 'הוסף ארוחה',
    foodPlaceholder: 'לדוגמה: "חזה עוף עם אורז" או "שייק חלבון"',
    add: 'הוסף',
    dbInfo: '300+ מזונות מוכרים במאגר. לא מוכר? בינה מלאכותית תעריך אוטומטית את הערכים התזונתיים.',
    dailySummary: 'סיכום יומי',
    outOf: 'מתוך',
    optimalProtein: 'חלוקת חלבון מיטבית:',
    proteinPerMealTip: 'גרם חלבון לארוחה,',
    mealInterval: 'במרווחי ~3 שעות לבניית שריר מיטבית',
    todayMeals: 'ארוחות היום',
    meals: 'ארוחות',
    added: 'נוסף:',
    caloriesWord: 'קלוריות',
    proteinGrams: 'גרם חלבון',
    aiEstimate: '(הערכת AI)',
    errorSaving: 'שגיאה בשמירת הארוחה',
    carbsShort: 'פחמ\'',

    // Workout Plan
    workoutPlan: 'תוכנית אימונים',
    upperLowerSplit: 'חלוקת פלג גוף עליון/תחתון',
    level: 'רמה',
    workoutDuration: 'משך אימון (דקות):',
    finishedWorkout: 'סיימתי אימון',
    sets: 'סטים',
    importantPrinciples: 'עקרונות חשובים',
    minSetsPerWeek: 'לפחות 10 סטים שבועיים לכל קבוצת שריר',
    consistencyMatters: 'עקביות > מורכבות - התמדה חשובה ממבנה אימון מתוחכם',
    workoutSaved: 'נרשם בהצלחה!',
    errorSavingWorkout: 'שגיאה בשמירת האימון',
    strength: 'כוח',
    hypertrophy: 'היפרטרופיה',
    cardio: 'אירובי',

    // Progress
    progress: 'התקדמות',
    trackProgress: 'מעקב אחר ההתקדמות שלך | מטרה:',
    streakDays: 'רצף אימונים (ימים)',
    totalWorkouts: 'סה"כ אימונים',
    workoutsThisWeek: 'אימונים השבוע',
    caloriesBurnedWeek: 'קלוריות שנשרפו השבוע',
    calorieProgressToday: 'התקדמות קלוריות היום',
    dailyCalories: 'קלוריות יומיות',
    remaining: 'נותרו',
    proteinProgressToday: 'התקדמות חלבון היום',
    dailyProtein: 'חלבון יומי',
    gramsRemaining: 'גרם נותרו',
    dietaryFiber: 'סיבים תזונתיים',
    dailyFiberTarget: 'גרם יעד יומי (בריאות המעי והגברת שובע)',
    weightGainTarget: 'יעד עלייה במשקל',
    weightMaintain: 'שמירה על משקל',
    weeklyLossTarget: 'יעד ירידה שבועי',
    perMonth: 'ק"ג / חודש',
    perWeek: 'ק"ג / שבוע',
    tooFastGain: 'עלייה מהירה מדי = צבירת שומן מיותרת',
    stableWeight: 'משקל יציב',
    normalRange: 'ק"ג הן נורמליות (מים, גליקוגן)',
    weeklyLossRate: 'ירידה של 0.5%-1.0% ממשקל הגוף בשבוע לשמירה על מסת שריר',
    recentWorkouts: 'אימונים אחרונים',
    workout: 'אימון',
    minutes: 'דקות',

    // Settings
    settings: 'הגדרות',
    settingsSubtitle: 'עדכן את הפרטים שלך כדי לקבל יעדים מדויקים',
    updateProfile: 'עדכון פרופיל',
    saveChanges: 'שמור שינויים',
    profileUpdated: 'הפרופיל עודכן בהצלחה!',
    errorUpdating: 'שגיאה בעדכון הפרופיל',
    settingsNote: 'שינוי המשקל, הגובה או המטרה יעדכן אוטומטית את כל היעדים התזונתיים ותוכנית האימונים שלך.',
    language: 'שפה',
    hebrew: 'עברית',
    english: 'English',

    // Exercise modal
    exerciseDetails: 'פרטי תרגיל',
    muscleGroup: 'קבוצת שריר',
    watchTutorial: 'צפה בסרטון הדרכה',
    close: 'סגור',
    howLong: 'כמה זמן אימנת? (דקות)',
    confirm: 'אישור',
    cancel: 'ביטול',

    // Workout notes
    note_keep_weights: 'שמור על משקלי העבודה - ירידה בכוח = סימן לגירעון אגרסיבי מדי',
    note_strength_before_cardio: 'אימון כוח לפני אירובי, הפרד ב-3-6 שעות',
    note_prefer_cycling: 'העדף אופניים/שחייה על ריצה - פחות פגיעה בשריר',
    note_minimum_volume: 'נפח אימון מינימלי (4-6 סטים לשריר בשבוע) - MV',
    note_high_intensity: 'שמור על עצימות גבוהה (RPE 8-9) - זה מה ששומר על שריר',
    note_no_need_increase: 'אין צורך להגדיל משקלים - שמירה על רמה נוכחית',
    note_zone2_cardio: 'ניתן להוסיף אירובי Zone 2 לבריאות לב-ריאה',
    note_progressive_overload: 'עלייה הדרגתית (Progressive Overload) - שיטת Double Progression',
    note_sets_per_muscle: '10-20 סטים לקבוצת שריר בשבוע לתוצאות מיטביות',
    note_track_weight_gain: 'עקוב אחרי עלייה במשקל: מתחילים 1-1.5%/חודש, מתקדמים 0.5-1%, מתאמנים מנוסים <0.5%',
    note_too_fast_gain: 'עלייה מהירה מדי = צבירת שומן מיותרת - התאם קלוריות',

    // Meal delete
    deleteMeal: 'מחק',
    mealDeleted: 'הארוחה נמחקה בהצלחה',
    errorDeleting: 'שגיאה במחיקת הארוחה',

    // BMI
    bmiAnalysis: 'ניתוח BMI',
    bmiValue: 'ערך BMI',
    bmiClassification: 'סיווג',
    bmiUnderweight: 'תת משקל',
    bmiNormal: 'משקל תקין',
    bmiOverweight: 'עודף משקל',
    bmiObese1: 'השמנה דרגה I',
    bmiObese2: 'השמנה דרגה II',
    bmiObese3: 'השמנה דרגה III',
    healthyWeightRange: 'טווח משקל בריא',
    targetWeight: 'משקל יעד',
    currentWeight: 'משקל נוכחי',
    weightToLose: 'יש להוריד',
    weightToGain: 'יש להעלות',
    weeklyRate: 'קצב שבועי',
    kgPerWeekRate: 'ק"ג/שבוע',
    estimatedTime: 'זמן משוער',
    weeks: 'שבועות',
    months: 'חודשים',
    dailyDeficit: 'גירעון קלורי יומי',
    dailySurplus: 'עודף קלורי יומי',
    bmiRecommendation: 'המלצה',
    bmiRecommendGoal: 'מטרה מומלצת',
    bmiAtHealthy: 'המשקל שלך בטווח הבריא! המשך לשמור על אורח חיים בריא.',
    bmiNeedToLose: 'מומלץ לרדת במשקל בקצב בריא ובטוח.',
    bmiNeedToGain: 'מומלץ להעלות במשקל בהדרגה עם תזונה עשירה.',
    applyRecommendation: 'החל המלצה',
    bmiApplied: 'המטרה עודכנה בהתאם להמלצת BMI!',
    bmiSimulator: 'סימולטור BMI',
    bmiSimulatorDesc: 'הזז את הנקודה כדי לראות איך שינוי במשקל ישפיע על ה-BMI שלך',
    simulatedWeight: 'משקל מדומה',
    yourBMIWouldBe: 'ה-BMI שלך יהיה',
    genderLabel: 'מין',

    // Sleep
    sleepTitle: 'מעקב שינה',
    sleepSubtitle: 'רשום את שעות השינה שלך וצבור XP',
    sleepLogToday: 'שינה של היום',
    sleepLogged: 'נרשם',
    sleepHours: 'שעות',
    sleepRecommended: 'מומלץ',
    sleepWorkoutBonus: 'שעה נוספת ביום אימון',
    sleepQuality: 'איכות השינה',
    sleepQuality_bad: 'גרוע',
    sleepQuality_ok: 'סביר',
    sleepQuality_good: 'טוב',
    sleepQuality_great: 'מעולה',
    sleepLog: 'שמור שינה',
    sleepUpdate: 'עדכן שינה',
    sleepSaved: 'נשמר',
    sleepWeeklyStats: 'סטטיסטיקה שבועית',
    sleepAvg: 'ממוצע',
    sleepGoalDays: 'עמידה ביעד',
    sleepLoggedDays: 'ימים שנרשמו',
    sleepHistory: '7 ימים אחרונים',
    sleepMinLine: 'מינימום מומלץ',
    sleepExcellent: 'מצוין',
    sleepGood: 'טוב',
    sleepFair: 'סביר',
    sleepPoor: 'לא מספיק',
    sleepXPInfo: 'איך צוברים XP משינה?',
    sleepXPGoal: 'עמידה ביעד השינה היומי = 25 XP',
    sleepXPStreak: 'רצף ימי שינה תקינה = הישגים מיוחדים',
    sleepXPBadges: 'הישגי שינה: 7, 14, 30 ימי רצף',
    xpSleepGoal: 'יעד שינה',
    xpSleepGreat: 'שינה מצוינת',

    // Daily Menu
    dailyMenu: 'תפריט יומי',
    dailyMenuBtn: 'תפריט יומי מומלץ',
    swapMenu: 'החלף תפריט',
    swapMeal: 'החלף ארוחה',
    menuBreakfast: 'ארוחת בוקר',
    menuSnack: 'חטיף',
    menuLunch: 'ארוחת צהריים',
    menuDinner: 'ארוחת ערב',
    menuTotal: 'סה"כ',
    menuMatchedTo: 'מותאם ליעד של',
    menuLoading: 'טוען תפריט...',
    menuError: 'שגיאה בטעינת תפריט',
    hideMenu: 'הסתר תפריט',

    // Admin
    tabAdmin: 'ניהול',
    adminDashboard: 'לוח בקרה',
    totalUsers: 'סה"כ משתמשים',
    activeUsersLabel: 'משתמשים פעילים',
    newThisWeek: 'חדשים השבוע',
    totalWorkoutsAdmin: 'סה"כ אימונים',
    workoutsThisWeekAdmin: 'אימונים השבוע',
    totalMealsAdmin: 'סה"כ ארוחות',
    userList: 'רשימת משתמשים',
    joinDate: 'תאריך הצטרפות',
    lastWorkoutDate: 'אימון אחרון',
    noWorkoutsYet: 'אין עדיין',
    admin: 'מנהל',

    // Duration selector
    availableTime: 'זמן זמין:',
    exercisesSkipped: 'תרגילים הוסרו',
    shortWorkoutNote: 'סטים מופחתים לאימון קצר',
    longWorkoutNote: 'סטים נוספו לאימון ארוך',
    gymWorkout: 'חדר כושר',
    homeWorkout: 'אימון בבית',
    deleteWorkout: 'מחק',
    workoutDeleted: 'האימון נמחק בהצלחה',
    errorDeletingWorkout: 'שגיאה במחיקת האימון',
    alreadyTrainedToday: 'כבר התאמנת היום! מחק את האימון כדי לרשום חדש',
    weeklyLimitReached: 'השלמת את כל האימונים השבוע! מנוחה חשובה',
    updateWeightReminder: 'עבר שבוע! עדכן את המשקל שלך בהגדרות כדי לעקוב אחרי ההתקדמות',
    clickForTutorial: 'לחץ על תרגיל לצפייה בסרטון הדרכה ביוטיוב ▶',
    undo: 'ביטול',

    // Progression / XP System
    tabProgression: 'XP',
    progressionTitle: 'המסע שלך',
    progressionSubtitle: 'צבור XP, עלה רמות וגלה הישגים',
    xpLevel: 'רמה',
    levelUp: 'עלית רמה!',
    levelUpMsg: 'הגעת לרמה',
    totalXP: 'סה"כ XP',
    xpToNext: 'XP לרמה הבאה',
    currentStreak: 'רצף פעילות',
    longestStreak: 'רצף יעד קלוריות',
    days: 'ימים',
    weekStreaks: 'שבועות רצופים',

    // XP Events
    xpWorkout: 'השלמת אימון',
    xpCalorieGoal: 'עמידה ביעד קלוריות',
    xpProteinGoal: 'עמידה ביעד חלבון',
    xpStreakDay: 'יום רצף',
    xpStreakWeek: 'בונוס שבוע רצוף',

    // Stats
    statDiscipline: 'משמעת אימונים',
    statStrength: 'חוזק',
    statRecovery: 'יעד משקל',
    statSleep: 'שינה',
    statsTitle: 'אחוזי התקדמות',

    // Badges
    badgesTitle: 'הישגים',
    badgeUnlocked: 'נפתח!',
    badgeLocked: 'נעול',
    badge_first_workout: 'צעד ראשון',
    badge_first_workout_desc: 'השלם את האימון הראשון',
    badge_workout_10: 'מתאמן מסור',
    badge_workout_10_desc: '10 אימונים',
    badge_workout_50: 'מכונת אימון',
    badge_workout_50_desc: '50 אימונים',
    badge_workout_100: 'אגדת כושר',
    badge_workout_100_desc: '100 אימונים',
    badge_streak_3: 'רצף 3 ימים',
    badge_streak_3_desc: 'רצף של 3 ימים',
    badge_streak_7: 'שבוע מושלם',
    badge_streak_7_desc: 'רצף של שבוע',
    badge_streak_14: 'שבועיים בלי עצירה',
    badge_streak_14_desc: 'רצף של שבועיים',
    badge_streak_30: 'חודש ברצף',
    badge_streak_30_desc: 'רצף של חודש שלם!',
    badge_level_5: 'חניך',
    badge_level_5_desc: 'הגעת לרמה 5',
    badge_level_10: 'לוחם',
    badge_level_10_desc: 'הגעת לרמה 10',
    badge_level_20: 'אלוף',
    badge_level_20_desc: 'הגעת לרמה 20',
    badge_nutrition_streak_7: 'אוכל נכון',
    badge_nutrition_streak_7_desc: 'שבוע של עמידה ביעדים',
    badge_nutrition_streak_4: 'מאסטר תזונה',
    badge_nutrition_streak_4_desc: '4 שבועות של עמידה ביעדים',
    badge_xp_1000: '1K מועדון',
    badge_xp_1000_desc: 'צבור 1,000 XP',
    badge_xp_5000: '5K מועדון',
    badge_xp_5000_desc: 'צבור 5,000 XP',
    badge_xp_10000: 'אליטה',
    badge_xp_10000_desc: 'צבור 10,000 XP',

    badge_workout_25: 'קבוע',
    badge_workout_25_desc: '25 אימונים',
    badge_workout_200: 'חייל כושר',
    badge_workout_200_desc: '200 אימונים',
    badge_streak_60: 'דרקון',
    badge_streak_60_desc: 'רצף של 60 יום',
    badge_streak_100: 'נשר',
    badge_streak_100_desc: 'רצף של 100 יום!',
    badge_level_3: 'נבט',
    badge_level_3_desc: 'הגעת לרמה 3',
    badge_level_15: 'מגן',
    badge_level_15_desc: 'הגעת לרמה 15',
    badge_level_30: 'יהלום',
    badge_level_30_desc: 'הגעת לרמה 30',
    badge_nutrition_streak_8: 'מדליסט תזונה',
    badge_nutrition_streak_8_desc: '8 שבועות של עמידה ביעדים',
    badge_nutrition_streak_12: 'שף מקצועי',
    badge_nutrition_streak_12_desc: '12 שבועות של עמידה ביעדים',
    badge_first_calorie_goal: 'יעד קלוריות ראשון',
    badge_first_calorie_goal_desc: 'עמוד ביעד קלוריות לראשונה',
    badge_first_protein_goal: 'יעד חלבון ראשון',
    badge_first_protein_goal_desc: 'עמוד ביעד חלבון לראשונה',
    badge_xp_500: 'מתחילים',
    badge_xp_500_desc: 'צבור 500 XP',
    badge_xp_2500: 'שחקן ותיק',
    badge_xp_2500_desc: 'צבור 2,500 XP',
    badge_xp_25000: 'שמש',
    badge_xp_25000_desc: 'צבור 25,000 XP',

    badge_first_sleep: 'לילה טוב',
    badge_first_sleep_desc: 'רשום שינה בפעם הראשונה',
    badge_sleep_7: 'שבוע של שינה',
    badge_sleep_7_desc: '7 ימי רצף של שינה תקינה',
    badge_sleep_14: 'שבועיים של שינה',
    badge_sleep_14_desc: '14 ימי רצף של שינה תקינה',
    badge_sleep_30: 'חודש של שינה',
    badge_sleep_30_desc: '30 ימי רצף של שינה תקינה',
    badge_sleep_logs_30: 'רושם שינה',
    badge_sleep_logs_30_desc: 'רשום 30 לילות שינה',
    badge_sleep_logs_100: 'מומחה שינה',
    badge_sleep_logs_100_desc: 'רשום 100 לילות שינה',

    recentActivity: 'פעילות אחרונה',
    xpGained: 'XP+',
  },

  en: {
    appName: 'Areto',

    tabOverview: 'Overview',
    tabWorkout: 'Workout Plan',
    tabNutrition: 'Nutrition',
    tabGoals: 'Goals',
    tabProgress: 'Progress',
    tabSettings: 'Settings',

    loginTitle: 'Log in to your account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginBtn: 'Log In',
    loggingIn: 'Logging in...',
    registerBtn: 'Sign Up',
    registering: 'Signing up...',
    registerSubtitle: 'Create a new account and start tracking your progress',
    noAccount: "Don't have an account?",
    registerHere: 'Sign up here',
    hasAccount: 'Already have an account?',
    loginHere: 'Log in here',
    fillAllFields: 'Please fill in all fields',
    passwordMin: 'Password must be at least 8 characters and include a digit',
    passwordMismatch: 'Passwords do not match',
    passwordPlaceholder: 'At least 6 characters',
    confirmPlaceholder: 'Enter password again',
    logout: 'Log Out',
    forgotPassword: 'Forgot password?',
    resetPassword: 'Reset Password',
    sendCode: 'Send Code',
    sendingCode: 'Sending...',
    enterCode: 'Enter the code sent to your email',
    codePlaceholder: '6-digit code',
    newPassword: 'New Password',
    resetBtn: 'Reset Password',
    resetting: 'Resetting...',
    codeSent: 'Code sent to your email',
    passwordResetSuccess: 'Password changed successfully! Log in with your new password',
    backToLogin: 'Back to Login',
    codeExpired: 'Code expired',
    wrongCode: 'Wrong code',

    nameLabel: 'First Name:',
    namePlaceholder: 'First name',
    helloName: 'Hello',

    onboardingTitle: "Let's get to know you",
    onboardingSubtitle: 'Tell us about yourself so we can create a personalized plan',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    age: 'Age',
    heightLabel: 'Height (cm)',
    weightLabel: 'Weight (kg)',
    bodyFat: 'Body Fat % (optional)',
    goalLabel: 'Goal',
    workoutsPerWeek: 'Workouts per week',
    workoutsUnit: 'workouts',
    experienceLabel: 'Experience Level',
    startJourney: 'Start your journey',
    saving: 'Saving...',
    fillRequired: 'Please fill in all required fields',

    goalBulk: 'Bulk',
    goalCut: 'Cut',
    goalMaintain: 'Maintain',
    goalBulkDesc: 'Build muscle and gain weight',
    goalCutDesc: 'Lose fat while preserving muscle',
    goalMaintainDesc: 'Maintain current weight',

    expBeginner: 'Beginner',
    expIntermediate: 'Intermediate',
    expAdvanced: 'Advanced',
    expBeginnerDesc: 'Less than 6 months training',
    expIntermediateDesc: '6 months to 2 years',
    expAdvancedDesc: 'Over 2 years of training',

    hello: 'Hello!',
    goal: 'Goal',
    weight: 'Weight',
    kg: 'kg',
    workoutsWeek: 'workouts/week',
    caloriesToday: 'Calories Today',
    proteinToday: 'Protein Today',
    workoutStreak: 'Workout Streak',
    dailyBurn: 'Daily Burn (cal)',
    burnedToday: 'Burned Today (workouts)',
    tipCalories: 'Total energy your body needs per day',
    tipProtein: 'Builds & repairs muscle - meat, eggs, legumes',
    tipCarbs: 'Main energy source - bread, rice, fruits',
    tipFat: 'Hormones & health - olive oil, avocado, nuts',
    tipFiber: 'Gut health & satiety - vegetables, fruits, whole grains',
    dailyProgress: 'Daily Progress',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
    kcal: 'kcal',
    grams: 'g',
    gramsPerKg: 'g/kg',
    yourNutritionTargets: 'Your Nutrition Targets',
    dailyCalorieTarget: 'Daily Calorie Target',
    proteinTip: 'Tip:',
    proteinPerMealText: 'protein per meal',
    mealsPerDay: 'meals/day',
    optimalMuscle: 'for optimal muscle building',
    gainTarget: 'Gain target:',
    kgPerMonth: 'kg/month',
    kgPerWeek: 'kg/week',
    maintenance: 'Maintain:',
    weightStable: 'Weight should stay stable (fluctuations up to ±',
    normalFluctuation: 'kg are normal)',
    weeklyTarget: 'Weekly target:',
    lossOf: 'Loss of',
    bodyWeightLoss: '(0.5%-1.0% of body weight to preserve muscle)',
    restBurn: 'Resting burn:',
    dailyBurnLabel: 'Daily burn:',

    nutritionTracking: 'Nutrition Tracking',
    nutritionSubtitle: 'Enter what you ate and the system will calculate nutritional values',
    addMeal: 'Add Meal',
    foodPlaceholder: 'e.g. "chicken breast with rice" or "protein shake"',
    add: 'Add',
    dbInfo: '300+ foods in database. Not found? AI will automatically estimate nutritional values.',
    dailySummary: 'Daily Summary',
    outOf: 'of',
    optimalProtein: 'Optimal protein distribution:',
    proteinPerMealTip: 'g protein per meal,',
    mealInterval: 'every ~3 hours for optimal muscle building',
    todayMeals: "Today's Meals",
    meals: 'meals',
    added: 'Added:',
    caloriesWord: 'calories',
    proteinGrams: 'g protein',
    aiEstimate: '(AI estimate)',
    errorSaving: 'Error saving meal',
    carbsShort: 'carbs',

    workoutPlan: 'Workout Plan',
    upperLowerSplit: 'Upper/Lower Split',
    level: 'Level',
    workoutDuration: 'Workout duration (min):',
    finishedWorkout: 'Finished',
    sets: 'sets',
    importantPrinciples: 'Key Principles',
    minSetsPerWeek: 'At least 10 weekly sets per muscle group',
    consistencyMatters: 'Consistency > complexity - persistence matters more than a fancy program',
    workoutSaved: 'saved successfully!',
    errorSavingWorkout: 'Error saving workout',
    strength: 'Strength',
    hypertrophy: 'Hypertrophy',
    cardio: 'Cardio',

    progress: 'Progress',
    trackProgress: 'Track your progress | Goal:',
    streakDays: 'Workout Streak (days)',
    totalWorkouts: 'Total Workouts',
    workoutsThisWeek: 'Workouts This Week',
    caloriesBurnedWeek: 'Calories Burned This Week',
    calorieProgressToday: "Today's Calorie Progress",
    dailyCalories: 'daily calories',
    remaining: 'remaining',
    proteinProgressToday: "Today's Protein Progress",
    dailyProtein: 'daily protein',
    gramsRemaining: 'g remaining',
    dietaryFiber: 'Dietary Fiber',
    dailyFiberTarget: 'g daily target (gut health & satiety)',
    weightGainTarget: 'Weight Gain Target',
    weightMaintain: 'Weight Maintenance',
    weeklyLossTarget: 'Weekly Loss Target',
    perMonth: 'kg / month',
    perWeek: 'kg / week',
    tooFastGain: 'Gaining too fast = unnecessary fat gain',
    stableWeight: 'Stable Weight',
    normalRange: 'kg is normal (water, glycogen)',
    weeklyLossRate: '0.5%-1.0% of body weight per week to preserve muscle mass',
    recentWorkouts: 'Recent Workouts',
    workout: 'Workout',
    minutes: 'min',

    settings: 'Settings',
    settingsSubtitle: 'Update your details for accurate targets',
    updateProfile: 'Update Profile',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated successfully!',
    errorUpdating: 'Error updating profile',
    settingsNote: 'Changing weight, height, or goal will automatically update all nutrition targets and workout plan.',
    language: 'Language',
    hebrew: 'עברית',
    english: 'English',

    exerciseDetails: 'Exercise Details',
    muscleGroup: 'Muscle Group',
    watchTutorial: 'Watch Tutorial Video',
    close: 'Close',
    howLong: 'How long did you train? (minutes)',
    confirm: 'Confirm',
    cancel: 'Cancel',

    // Workout notes
    note_keep_weights: 'Maintain working weights - strength loss = sign of too aggressive deficit',
    note_strength_before_cardio: 'Strength training before cardio, separate by 3-6 hours',
    note_prefer_cycling: 'Prefer cycling/swimming over running - less muscle damage',
    note_minimum_volume: 'Minimum training volume (4-6 sets per muscle per week) - MV',
    note_high_intensity: 'Keep high intensity (RPE 8-9) - this is what preserves muscle',
    note_no_need_increase: 'No need to increase weights - maintain current level',
    note_zone2_cardio: 'You can add Zone 2 cardio for cardiovascular health',
    note_progressive_overload: 'Progressive Overload - Double Progression method',
    note_sets_per_muscle: '10-20 sets per muscle group per week for optimal results',
    note_track_weight_gain: 'Track weight gain: beginners 1-1.5%/month, intermediate 0.5-1%, advanced <0.5%',
    note_too_fast_gain: 'Gaining too fast = unnecessary fat gain - adjust calories',

    // Meal delete
    deleteMeal: 'Delete',
    mealDeleted: 'Meal deleted successfully',
    errorDeleting: 'Error deleting meal',

    // BMI
    bmiAnalysis: 'BMI Analysis',
    bmiValue: 'BMI Value',
    bmiClassification: 'Classification',
    bmiUnderweight: 'Underweight',
    bmiNormal: 'Normal Weight',
    bmiOverweight: 'Overweight',
    bmiObese1: 'Obese Class I',
    bmiObese2: 'Obese Class II',
    bmiObese3: 'Obese Class III',
    healthyWeightRange: 'Healthy Weight Range',
    targetWeight: 'Target Weight',
    currentWeight: 'Current Weight',
    weightToLose: 'Need to lose',
    weightToGain: 'Need to gain',
    weeklyRate: 'Weekly Rate',
    kgPerWeekRate: 'kg/week',
    estimatedTime: 'Estimated Time',
    weeks: 'weeks',
    months: 'months',
    dailyDeficit: 'Daily Caloric Deficit',
    dailySurplus: 'Daily Caloric Surplus',
    bmiRecommendation: 'Recommendation',
    bmiRecommendGoal: 'Recommended Goal',
    bmiAtHealthy: 'Your weight is in the healthy range! Keep up the healthy lifestyle.',
    bmiNeedToLose: 'We recommend losing weight at a healthy and safe pace.',
    bmiNeedToGain: 'We recommend gaining weight gradually with a nutritious diet.',
    applyRecommendation: 'Apply Recommendation',
    bmiApplied: 'Goal updated based on BMI recommendation!',
    bmiSimulator: 'BMI Simulator',
    bmiSimulatorDesc: 'Drag the dot to see how weight changes affect your BMI',
    simulatedWeight: 'Simulated Weight',
    yourBMIWouldBe: 'Your BMI would be',
    genderLabel: 'Gender',

    // Sleep
    sleepTitle: 'Sleep Tracking',
    sleepSubtitle: 'Log your sleep hours and earn XP',
    sleepLogToday: "Today's Sleep",
    sleepLogged: 'Logged',
    sleepHours: 'hours',
    sleepRecommended: 'Recommended',
    sleepWorkoutBonus: 'extra hour on workout day',
    sleepQuality: 'Sleep Quality',
    sleepQuality_bad: 'Bad',
    sleepQuality_ok: 'OK',
    sleepQuality_good: 'Good',
    sleepQuality_great: 'Great',
    sleepLog: 'Log Sleep',
    sleepUpdate: 'Update Sleep',
    sleepSaved: 'Saved',
    sleepWeeklyStats: 'Weekly Stats',
    sleepAvg: 'Average',
    sleepGoalDays: 'Goal Met',
    sleepLoggedDays: 'Days Logged',
    sleepHistory: 'Last 7 Days',
    sleepMinLine: 'Recommended minimum',
    sleepExcellent: 'Excellent',
    sleepGood: 'Good',
    sleepFair: 'Fair',
    sleepPoor: 'Not enough',
    sleepXPInfo: 'How to earn XP from sleep?',
    sleepXPGoal: 'Meet daily sleep goal = 25 XP',
    sleepXPStreak: 'Consecutive days of good sleep = special badges',
    sleepXPBadges: 'Sleep badges: 7, 14, 30 day streaks',
    xpSleepGoal: 'Sleep Goal',
    xpSleepGreat: 'Great Sleep',

    // Daily Menu
    dailyMenu: 'Daily Menu',
    dailyMenuBtn: 'Suggested Daily Menu',
    swapMenu: 'Swap Menu',
    swapMeal: 'Swap Meal',
    menuBreakfast: 'Breakfast',
    menuSnack: 'Snack',
    menuLunch: 'Lunch',
    menuDinner: 'Dinner',
    menuTotal: 'Total',
    menuMatchedTo: 'Matched to target of',
    menuLoading: 'Loading menu...',
    menuError: 'Error loading menu',
    hideMenu: 'Hide Menu',

    // Admin
    tabAdmin: 'Admin',
    adminDashboard: 'Admin Dashboard',
    totalUsers: 'Total Users',
    activeUsersLabel: 'Active Users',
    newThisWeek: 'New This Week',
    totalWorkoutsAdmin: 'Total Workouts',
    workoutsThisWeekAdmin: 'Workouts This Week',
    totalMealsAdmin: 'Total Meals',
    userList: 'User List',
    joinDate: 'Joined',
    lastWorkoutDate: 'Last Workout',
    noWorkoutsYet: 'None yet',
    admin: 'Admin',

    // Duration selector
    availableTime: 'Available time:',
    exercisesSkipped: 'exercises removed',
    shortWorkoutNote: 'Fewer sets for short workout',
    longWorkoutNote: 'Extra sets added for longer workout',
    gymWorkout: 'Gym',
    homeWorkout: 'Home Workout',
    deleteWorkout: 'Delete',
    workoutDeleted: 'Workout deleted successfully',
    errorDeletingWorkout: 'Error deleting workout',
    alreadyTrainedToday: 'Already trained today! Delete the workout to log a new one',
    weeklyLimitReached: 'You completed all workouts this week! Rest is important',
    updateWeightReminder: 'A week has passed! Update your weight in Settings to track your progress',
    clickForTutorial: 'Click on an exercise to watch a YouTube tutorial',
    undo: 'Undo',

    // Progression / XP System
    tabProgression: 'XP',
    progressionTitle: 'Your Journey',
    progressionSubtitle: 'Earn XP, level up, and unlock achievements',
    xpLevel: 'Level',
    levelUp: 'Level Up!',
    levelUpMsg: 'You reached level',
    totalXP: 'Total XP',
    xpToNext: 'XP to next level',
    currentStreak: 'Activity Streak',
    longestStreak: 'Calorie Goal Streak',
    days: 'days',
    weekStreaks: 'Week Streaks',

    xpWorkout: 'Workout Completed',
    xpCalorieGoal: 'Calorie Goal Met',
    xpProteinGoal: 'Protein Goal Met',
    xpStreakDay: 'Streak Day',
    xpStreakWeek: 'Weekly Streak Bonus',

    statDiscipline: 'Workout Discipline',
    statStrength: 'Strength',
    statRecovery: 'Weight Goal',
    statSleep: 'Sleep',
    statsTitle: 'Progress Rates',

    badgesTitle: 'Achievements',
    badgeUnlocked: 'Unlocked!',
    badgeLocked: 'Locked',
    badge_first_workout: 'First Step',
    badge_first_workout_desc: 'Complete your first workout',
    badge_workout_10: 'Dedicated',
    badge_workout_10_desc: '10 workouts',
    badge_workout_50: 'Workout Machine',
    badge_workout_50_desc: '50 workouts',
    badge_workout_100: 'Fitness Legend',
    badge_workout_100_desc: '100 workouts',
    badge_streak_3: '3 Day Streak',
    badge_streak_3_desc: '3 day streak',
    badge_streak_7: 'Perfect Week',
    badge_streak_7_desc: '7 day streak',
    badge_streak_14: 'Unstoppable',
    badge_streak_14_desc: '14 day streak',
    badge_streak_30: 'Monthly Champion',
    badge_streak_30_desc: '30 day streak!',
    badge_level_5: 'Apprentice',
    badge_level_5_desc: 'Reach level 5',
    badge_level_10: 'Warrior',
    badge_level_10_desc: 'Reach level 10',
    badge_level_20: 'Champion',
    badge_level_20_desc: 'Reach level 20',
    badge_nutrition_streak_7: 'Clean Eater',
    badge_nutrition_streak_7_desc: 'A week of hitting goals',
    badge_nutrition_streak_4: 'Nutrition Master',
    badge_nutrition_streak_4_desc: '4 weeks of hitting goals',
    badge_xp_1000: '1K Club',
    badge_xp_1000_desc: 'Earn 1,000 XP',
    badge_xp_5000: '5K Club',
    badge_xp_5000_desc: 'Earn 5,000 XP',
    badge_xp_10000: 'Elite',
    badge_xp_10000_desc: 'Earn 10,000 XP',

    badge_workout_25: 'Regular',
    badge_workout_25_desc: '25 workouts',
    badge_workout_200: 'Fitness Soldier',
    badge_workout_200_desc: '200 workouts',
    badge_streak_60: 'Dragon',
    badge_streak_60_desc: '60 day streak',
    badge_streak_100: 'Eagle',
    badge_streak_100_desc: '100 day streak!',
    badge_level_3: 'Sprout',
    badge_level_3_desc: 'Reach level 3',
    badge_level_15: 'Shield',
    badge_level_15_desc: 'Reach level 15',
    badge_level_30: 'Diamond',
    badge_level_30_desc: 'Reach level 30',
    badge_nutrition_streak_8: 'Nutrition Medalist',
    badge_nutrition_streak_8_desc: '8 weeks of hitting goals',
    badge_nutrition_streak_12: 'Pro Chef',
    badge_nutrition_streak_12_desc: '12 weeks of hitting goals',
    badge_first_calorie_goal: 'First Calorie Goal',
    badge_first_calorie_goal_desc: 'Hit your calorie goal for the first time',
    badge_first_protein_goal: 'First Protein Goal',
    badge_first_protein_goal_desc: 'Hit your protein goal for the first time',
    badge_xp_500: 'Getting Started',
    badge_xp_500_desc: 'Earn 500 XP',
    badge_xp_2500: 'Veteran',
    badge_xp_2500_desc: 'Earn 2,500 XP',
    badge_xp_25000: 'Sunshine',
    badge_xp_25000_desc: 'Earn 25,000 XP',

    badge_first_sleep: 'Good Night',
    badge_first_sleep_desc: 'Log sleep for the first time',
    badge_sleep_7: 'Sleep Week',
    badge_sleep_7_desc: '7-day streak of meeting sleep goal',
    badge_sleep_14: 'Sleep Fortnight',
    badge_sleep_14_desc: '14-day streak of meeting sleep goal',
    badge_sleep_30: 'Sleep Month',
    badge_sleep_30_desc: '30-day streak of meeting sleep goal',
    badge_sleep_logs_30: 'Sleep Logger',
    badge_sleep_logs_30_desc: 'Log 30 nights of sleep',
    badge_sleep_logs_100: 'Sleep Expert',
    badge_sleep_logs_100_desc: 'Log 100 nights of sleep',

    recentActivity: 'Recent Activity',
    xpGained: 'XP+',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'he');

  function setLanguage(l) {
    setLang(l);
    localStorage.setItem('lang', l);
    document.documentElement.dir = l === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = l;
  }

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
