import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  he: {
    // App name
    appName: 'פיטטרק',

    // Tabs
    tabOverview: 'סקירה כללית',
    tabWorkout: 'תוכנית אימונים',
    tabNutrition: 'תזונה',
    tabProgress: 'התקדמות',
    tabSettings: 'הגדרות',

    // Auth
    loginTitle: 'התחבר לחשבון שלך',
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אימות סיסמה',
    loginBtn: 'התחברות',
    loggingIn: 'מתחבר...',
    registerBtn: 'הרשמה',
    registering: 'נרשם...',
    registerSubtitle: 'צור חשבון חדש והתחל לעקוב אחרי ההתקדמות שלך',
    noAccount: 'עדיין אין לך חשבון?',
    registerHere: 'הירשם כאן',
    hasAccount: 'יש לך כבר חשבון?',
    loginHere: 'התחבר כאן',
    fillAllFields: 'יש למלא את כל השדות',
    passwordMin: 'הסיסמה חייבת להכיל לפחות 6 תווים',
    passwordMismatch: 'הסיסמאות אינן תואמות',
    passwordPlaceholder: 'לפחות 6 תווים',
    confirmPlaceholder: 'הזן את הסיסמה שוב',
    logout: 'התנתקות',

    // Onboarding
    onboardingTitle: 'בוא נכיר אותך',
    onboardingSubtitle: 'ספר לנו קצת על עצמך כדי שנתאים לך תוכנית אישית',
    gender: 'מין',
    male: 'גבר',
    female: 'אישה',
    age: 'גיל',
    heightLabel: 'גובה (ס"מ)',
    weightLabel: 'משקל (ק"ג)',
    bodyFat: 'אחוז שומן (אופציונלי)',
    goalLabel: 'מטרה',
    workoutsPerWeek: 'מספר אימונים בשבוע',
    workoutsUnit: 'אימונים',
    experienceLabel: 'רמת ניסיון',
    startJourney: 'התחל את המסע שלך',
    saving: 'שומר...',
    fillRequired: 'יש למלא את כל השדות הנדרשים',

    // Goals
    goalBulk: 'עלייה במסה',
    goalCut: 'חיטוב',
    goalMaintain: 'שמירה',
    goalBulkDesc: 'בניית שריר ועלייה במשקל',
    goalCutDesc: 'ירידה באחוזי שומן עם שימור שריר',
    goalMaintainDesc: 'שמירה על המשקל הנוכחי',

    // Experience
    expBeginner: 'מתחיל',
    expIntermediate: 'בינוני',
    expAdvanced: 'מתקדם',
    expBeginnerDesc: 'פחות מ-6 חודשי אימון',
    expIntermediateDesc: '6 חודשים עד 2 שנים',
    expAdvancedDesc: 'מעל 2 שנות אימון',

    // Overview
    hello: 'שלום! 👋',
    goal: 'מטרה',
    weight: 'משקל',
    kg: 'ק"ג',
    workoutsWeek: 'אימונים בשבוע',
    caloriesToday: 'קלוריות היום',
    proteinToday: 'חלבון היום',
    workoutStreak: 'רצף אימונים',
    dailyBurn: 'שריפה יומית (קלוריות)',
    burnedToday: 'נשרף היום מאימונים',
    tipCalories: 'סה"כ אנרגיה שהגוף צריך ביום',
    tipProtein: 'בניית שריר ותיקון רקמות - בשר, ביצים, קטניות',
    tipCarbs: 'מקור האנרגיה העיקרי - לחם, אורז, פירות',
    tipFat: 'הורמונים ובריאות - שמן זית, אבוקדו, אגוזים',
    tipFiber: 'בריאות מעיים ושובע - ירקות, פירות, דגנים מלאים',
    dailyProgress: 'התקדמות יומית',
    calories: 'קלוריות',
    protein: 'חלבון',
    carbs: 'פחמימות',
    fat: 'שומן',
    fiber: 'סיבים',
    kcal: 'קק"ל',
    grams: 'גרם',
    gramsPerKg: 'גרם/ק"ג',
    yourNutritionTargets: 'יעדי התזונה שלך',
    dailyCalorieTarget: 'יעד קלוריות יומי',
    proteinTip: 'טיפ:',
    proteinPerMealText: 'חלבון לארוחה',
    mealsPerDay: 'ארוחות ביום',
    optimalMuscle: 'לבניית שריר מיטבית',
    gainTarget: 'יעד עלייה:',
    kgPerMonth: 'ק"ג בחודש',
    kgPerWeek: 'ק"ג בשבוע',
    maintenance: 'שמירה:',
    weightStable: 'המשקל צריך להישאר יציב (תנודות של עד ±',
    normalFluctuation: 'ק"ג זה נורמלי)',
    weeklyTarget: 'יעד שבועי:',
    lossOf: 'ירידה של',
    bodyWeightLoss: '(0.5%-1.0% ממשקל הגוף לשמירה על שריר)',
    restBurn: 'שריפה במנוחה:',
    dailyBurnLabel: 'שריפה יומית:',

    // Nutrition Tracker
    nutritionTracking: 'מעקב תזונה 🍽️',
    nutritionSubtitle: 'הזן את מה שאכלת והמערכת תחשב את הערכים התזונתיים',
    addMeal: 'הוסף ארוחה',
    foodPlaceholder: 'לדוגמה: "חזה עוף עם אורז" או "שייק חלבון"',
    add: 'הוסף',
    dbInfo: '300+ מזונות מוכרים במאגר. לא מוכר? 🤖 בינה מלאכותית תעריך אוטומטית את הערכים התזונתיים.',
    dailySummary: 'סיכום יומי',
    outOf: 'מתוך',
    optimalProtein: 'חלוקת חלבון מיטבית:',
    proteinPerMealTip: 'גרם חלבון לארוחה,',
    mealInterval: 'במרווחי ~3 שעות לבניית שריר מיטבית',
    todayMeals: 'ארוחות היום',
    meals: 'ארוחות',
    added: 'נוסף:',
    caloriesWord: 'קלוריות',
    proteinGrams: 'גרם חלבון',
    aiEstimate: '(הערכת AI)',
    errorSaving: 'שגיאה בשמירת הארוחה',
    carbsShort: 'פחמ\'',

    // Workout Plan
    workoutPlan: 'תוכנית אימונים 🏋️',
    upperLowerSplit: 'חלוקת פלג גוף עליון/תחתון',
    level: 'רמה',
    workoutDuration: 'משך אימון (דקות):',
    finishedWorkout: 'סיימתי אימון ✓',
    sets: 'סטים',
    importantPrinciples: 'עקרונות חשובים',
    minSetsPerWeek: 'לפחות 10 סטים שבועיים לכל קבוצת שריר',
    consistencyMatters: 'עקביות > מורכבות - התמדה חשובה ממבנה אימון מתוחכם',
    workoutSaved: 'נרשם בהצלחה!',
    errorSavingWorkout: 'שגיאה בשמירת האימון',
    strength: 'כוח',
    hypertrophy: 'היפרטרופיה',
    cardio: 'אירובי',

    // Progress
    progress: 'התקדמות 📈',
    trackProgress: 'מעקב אחר ההתקדמות שלך | מטרה:',
    streakDays: 'רצף אימונים (ימים)',
    totalWorkouts: 'סה"כ אימונים',
    workoutsThisWeek: 'אימונים השבוע',
    caloriesBurnedWeek: 'קלוריות שנשרפו השבוע',
    calorieProgressToday: 'התקדמות קלוריות היום',
    dailyCalories: 'קלוריות יומיות',
    remaining: 'נותרו',
    proteinProgressToday: 'התקדמות חלבון היום',
    dailyProtein: 'חלבון יומי',
    gramsRemaining: 'גרם נותרו',
    dietaryFiber: 'סיבים תזונתיים',
    dailyFiberTarget: 'גרם יעד יומי (בריאות המעי והגברת שובע)',
    weightGainTarget: 'יעד עלייה במשקל',
    weightMaintain: 'שמירה על משקל',
    weeklyLossTarget: 'יעד ירידה שבועי',
    perMonth: 'ק"ג / חודש',
    perWeek: 'ק"ג / שבוע',
    tooFastGain: 'עלייה מהירה מדי = צבירת שומן מיותרת',
    stableWeight: 'משקל יציב',
    normalRange: 'ק"ג הן נורמליות (מים, גליקוגן)',
    weeklyLossRate: 'ירידה של 0.5%-1.0% ממשקל הגוף בשבוע לשמירה על מסת שריר',
    recentWorkouts: 'אימונים אחרונים',
    workout: 'אימון',
    minutes: 'דקות',

    // Settings
    settings: 'הגדרות ⚙️',
    settingsSubtitle: 'עדכן את הפרטים שלך כדי לקבל יעדים מדויקים',
    updateProfile: 'עדכון פרופיל',
    saveChanges: 'שמור שינויים',
    profileUpdated: 'הפרופיל עודכן בהצלחה!',
    errorUpdating: 'שגיאה בעדכון הפרופיל',
    settingsNote: 'שינוי המשקל, הגובה או המטרה יעדכן אוטומטית את כל היעדים התזונתיים ותוכנית האימונים שלך.',
    language: 'שפה',
    hebrew: 'עברית',
    english: 'English',

    // Exercise modal
    exerciseDetails: 'פרטי תרגיל',
    muscleGroup: 'קבוצת שריר',
    watchTutorial: 'צפה בסרטון הדרכה',
    close: 'סגור',
    howLong: 'כמה זמן אימנת? (דקות)',
    confirm: 'אישור',
    cancel: 'ביטול',

    // Workout notes
    note_keep_weights: 'שמור על משקלי העבודה - ירידה בכוח = סימן לגירעון אגרסיבי מדי',
    note_strength_before_cardio: 'אימון כוח לפני אירובי, הפרד ב-3-6 שעות',
    note_prefer_cycling: 'העדף אופניים/שחייה על ריצה - פחות פגיעה בשריר',
    note_minimum_volume: 'נפח אימון מינימלי (4-6 סטים לשריר בשבוע) - MV',
    note_high_intensity: 'שמור על עצימות גבוהה (RPE 8-9) - זה מה ששומר על שריר',
    note_no_need_increase: 'אין צורך להגדיל משקלים - שמירה על רמה נוכחית',
    note_zone2_cardio: 'ניתן להוסיף אירובי Zone 2 לבריאות לב-ריאה',
    note_progressive_overload: 'עלייה הדרגתית (Progressive Overload) - שיטת Double Progression',
    note_sets_per_muscle: '10-20 סטים לקבוצת שריר בשבוע לתוצאות מיטביות',
    note_track_weight_gain: 'עקוב אחרי עלייה במשקל: מתחילים 1-1.5%/חודש, מתקדמים 0.5-1%, מתאמנים מנוסים <0.5%',
    note_too_fast_gain: 'עלייה מהירה מדי = צבירת שומן מיותרת - התאם קלוריות',

    // Meal delete
    deleteMeal: 'מחק',
    mealDeleted: 'הארוחה נמחקה בהצלחה',
    errorDeleting: 'שגיאה במחיקת הארוחה',

    // Duration selector
    availableTime: 'זמן זמין:',
    exercisesSkipped: 'תרגילים הוסרו',
    shortWorkoutNote: 'סטים מופחתים לאימון קצר',
    longWorkoutNote: 'סטים נוספו לאימון ארוך',
    gymWorkout: 'חדר כושר',
    homeWorkout: 'אימון בבית',
  },

  en: {
    appName: 'FitTrack',

    tabOverview: 'Overview',
    tabWorkout: 'Workout Plan',
    tabNutrition: 'Nutrition',
    tabProgress: 'Progress',
    tabSettings: 'Settings',

    loginTitle: 'Log in to your account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginBtn: 'Log In',
    loggingIn: 'Logging in...',
    registerBtn: 'Sign Up',
    registering: 'Signing up...',
    registerSubtitle: 'Create a new account and start tracking your progress',
    noAccount: "Don't have an account?",
    registerHere: 'Sign up here',
    hasAccount: 'Already have an account?',
    loginHere: 'Log in here',
    fillAllFields: 'Please fill in all fields',
    passwordMin: 'Password must be at least 6 characters',
    passwordMismatch: 'Passwords do not match',
    passwordPlaceholder: 'At least 6 characters',
    confirmPlaceholder: 'Enter password again',
    logout: 'Log Out',

    onboardingTitle: "Let's get to know you",
    onboardingSubtitle: 'Tell us about yourself so we can create a personalized plan',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    age: 'Age',
    heightLabel: 'Height (cm)',
    weightLabel: 'Weight (kg)',
    bodyFat: 'Body Fat % (optional)',
    goalLabel: 'Goal',
    workoutsPerWeek: 'Workouts per week',
    workoutsUnit: 'workouts',
    experienceLabel: 'Experience Level',
    startJourney: 'Start your journey',
    saving: 'Saving...',
    fillRequired: 'Please fill in all required fields',

    goalBulk: 'Bulk',
    goalCut: 'Cut',
    goalMaintain: 'Maintain',
    goalBulkDesc: 'Build muscle and gain weight',
    goalCutDesc: 'Lose fat while preserving muscle',
    goalMaintainDesc: 'Maintain current weight',

    expBeginner: 'Beginner',
    expIntermediate: 'Intermediate',
    expAdvanced: 'Advanced',
    expBeginnerDesc: 'Less than 6 months training',
    expIntermediateDesc: '6 months to 2 years',
    expAdvancedDesc: 'Over 2 years of training',

    hello: 'Hello! 👋',
    goal: 'Goal',
    weight: 'Weight',
    kg: 'kg',
    workoutsWeek: 'workouts/week',
    caloriesToday: 'Calories Today',
    proteinToday: 'Protein Today',
    workoutStreak: 'Workout Streak',
    dailyBurn: 'Daily Burn (cal)',
    burnedToday: 'Burned Today (workouts)',
    tipCalories: 'Total energy your body needs per day',
    tipProtein: 'Builds & repairs muscle - meat, eggs, legumes',
    tipCarbs: 'Main energy source - bread, rice, fruits',
    tipFat: 'Hormones & health - olive oil, avocado, nuts',
    tipFiber: 'Gut health & satiety - vegetables, fruits, whole grains',
    dailyProgress: 'Daily Progress',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
    kcal: 'kcal',
    grams: 'g',
    gramsPerKg: 'g/kg',
    yourNutritionTargets: 'Your Nutrition Targets',
    dailyCalorieTarget: 'Daily Calorie Target',
    proteinTip: 'Tip:',
    proteinPerMealText: 'protein per meal',
    mealsPerDay: 'meals/day',
    optimalMuscle: 'for optimal muscle building',
    gainTarget: 'Gain target:',
    kgPerMonth: 'kg/month',
    kgPerWeek: 'kg/week',
    maintenance: 'Maintain:',
    weightStable: 'Weight should stay stable (fluctuations up to ±',
    normalFluctuation: 'kg are normal)',
    weeklyTarget: 'Weekly target:',
    lossOf: 'Loss of',
    bodyWeightLoss: '(0.5%-1.0% of body weight to preserve muscle)',
    restBurn: 'Resting burn:',
    dailyBurnLabel: 'Daily burn:',

    nutritionTracking: 'Nutrition Tracking 🍽️',
    nutritionSubtitle: 'Enter what you ate and the system will calculate nutritional values',
    addMeal: 'Add Meal',
    foodPlaceholder: 'e.g. "chicken breast with rice" or "protein shake"',
    add: 'Add',
    dbInfo: '300+ foods in database. Not found? 🤖 AI will automatically estimate nutritional values.',
    dailySummary: 'Daily Summary',
    outOf: 'of',
    optimalProtein: 'Optimal protein distribution:',
    proteinPerMealTip: 'g protein per meal,',
    mealInterval: 'every ~3 hours for optimal muscle building',
    todayMeals: "Today's Meals",
    meals: 'meals',
    added: 'Added:',
    caloriesWord: 'calories',
    proteinGrams: 'g protein',
    aiEstimate: '(AI estimate)',
    errorSaving: 'Error saving meal',
    carbsShort: 'carbs',

    workoutPlan: 'Workout Plan 🏋️',
    upperLowerSplit: 'Upper/Lower Split',
    level: 'Level',
    workoutDuration: 'Workout duration (min):',
    finishedWorkout: 'Finished ✓',
    sets: 'sets',
    importantPrinciples: 'Key Principles',
    minSetsPerWeek: 'At least 10 weekly sets per muscle group',
    consistencyMatters: 'Consistency > complexity - persistence matters more than a fancy program',
    workoutSaved: 'saved successfully!',
    errorSavingWorkout: 'Error saving workout',
    strength: 'Strength',
    hypertrophy: 'Hypertrophy',
    cardio: 'Cardio',

    progress: 'Progress 📈',
    trackProgress: 'Track your progress | Goal:',
    streakDays: 'Workout Streak (days)',
    totalWorkouts: 'Total Workouts',
    workoutsThisWeek: 'Workouts This Week',
    caloriesBurnedWeek: 'Calories Burned This Week',
    calorieProgressToday: "Today's Calorie Progress",
    dailyCalories: 'daily calories',
    remaining: 'remaining',
    proteinProgressToday: "Today's Protein Progress",
    dailyProtein: 'daily protein',
    gramsRemaining: 'g remaining',
    dietaryFiber: 'Dietary Fiber',
    dailyFiberTarget: 'g daily target (gut health & satiety)',
    weightGainTarget: 'Weight Gain Target',
    weightMaintain: 'Weight Maintenance',
    weeklyLossTarget: 'Weekly Loss Target',
    perMonth: 'kg / month',
    perWeek: 'kg / week',
    tooFastGain: 'Gaining too fast = unnecessary fat gain',
    stableWeight: 'Stable Weight',
    normalRange: 'kg is normal (water, glycogen)',
    weeklyLossRate: '0.5%-1.0% of body weight per week to preserve muscle mass',
    recentWorkouts: 'Recent Workouts',
    workout: 'Workout',
    minutes: 'min',

    settings: 'Settings ⚙️',
    settingsSubtitle: 'Update your details for accurate targets',
    updateProfile: 'Update Profile',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated successfully!',
    errorUpdating: 'Error updating profile',
    settingsNote: 'Changing weight, height, or goal will automatically update all nutrition targets and workout plan.',
    language: 'Language',
    hebrew: 'עברית',
    english: 'English',

    exerciseDetails: 'Exercise Details',
    muscleGroup: 'Muscle Group',
    watchTutorial: 'Watch Tutorial Video',
    close: 'Close',
    howLong: 'How long did you train? (minutes)',
    confirm: 'Confirm',
    cancel: 'Cancel',

    // Workout notes
    note_keep_weights: 'Maintain working weights - strength loss = sign of too aggressive deficit',
    note_strength_before_cardio: 'Strength training before cardio, separate by 3-6 hours',
    note_prefer_cycling: 'Prefer cycling/swimming over running - less muscle damage',
    note_minimum_volume: 'Minimum training volume (4-6 sets per muscle per week) - MV',
    note_high_intensity: 'Keep high intensity (RPE 8-9) - this is what preserves muscle',
    note_no_need_increase: 'No need to increase weights - maintain current level',
    note_zone2_cardio: 'You can add Zone 2 cardio for cardiovascular health',
    note_progressive_overload: 'Progressive Overload - Double Progression method',
    note_sets_per_muscle: '10-20 sets per muscle group per week for optimal results',
    note_track_weight_gain: 'Track weight gain: beginners 1-1.5%/month, intermediate 0.5-1%, advanced <0.5%',
    note_too_fast_gain: 'Gaining too fast = unnecessary fat gain - adjust calories',

    // Meal delete
    deleteMeal: 'Delete',
    mealDeleted: 'Meal deleted successfully',
    errorDeleting: 'Error deleting meal',

    // Duration selector
    availableTime: 'Available time:',
    exercisesSkipped: 'exercises removed',
    shortWorkoutNote: 'Fewer sets for short workout',
    longWorkoutNote: 'Extra sets added for longer workout',
    gymWorkout: 'Gym',
    homeWorkout: 'Home Workout',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'he');

  function setLanguage(l) {
    setLang(l);
    localStorage.setItem('lang', l);
    document.documentElement.dir = l === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = l;
  }

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
